### ISSUE TITLE
android上使用，显示连接成功但是上不了网咋解决啊

### ISSUE THREAD

**Issue by kuanglinfeng** [PandaVPN/panda#1]

**Comment by YeziXuannao** [comment]
更换其他节点，有很多节点都不太好用的，但是也有很多很好用的节点

**Comment by PandaVPN** [comment]
安卓手机使用，建议在手机设置-应用管理里面找到PandaVPN，点击清理下客户端缓存数据，重新连接线路试试。若是仍有问题，可以通过应用内在线反馈联系客服解决。
