### ISSUE TITLE
请大家千万检查自己有无自动续费！！

### ISSUE THREAD

**Issue by soloice** [PandaVPN/panda#103]
我的付款方式是 paymentwall，12月11号的时候（就是 panda 已经不能用了以后）它给我自动续费了！！！真的给我整麻了！！！

![payment](https://user-images.githubusercontent.com/8534653/208253449-e26fd43d-98ca-4b12-932d-a2cae90a212b.PNG)

我发现 support@paymentwall.com 其实会在续费前几天（我是 12 月 4 号收到的）发邮件提醒，里面可以点取消，但我没注意……
![paymentwall](https://user-images.githubusercontent.com/8534653/208253546-136679fd-2916-4925-bfa3-e6acbb814a2a.PNG)

我现在点了取消，至少两年以后不会给我再续了吧……

我没找到怎么在 panda 账户里查看有没有自动续订，只能提醒用 paymentwall 支付的朋友及时查收邮件、取消自动续费！我给 paymentwall 也发了邮件，不知道钱能不能要回来。

**Comment by uglyliu** [comment]
> 我的付款方式是 paymentwall，12月11号的时候（就是 panda 已经不能用了以后）它给我自动续费了！！！真的给我整麻了！！！
> 
> 
> 
> ![payment](https://user-images.githubusercontent.com/8534653/208253449-e26fd43d-98ca-4b12-932d-a2cae90a212b.PNG)
> 
> 
> 
> 我发现 support@paymentwall.com 其实会在续费前几天（我是 12 月 4 号收到的）发邮件提醒，里面可以点取消，但我没注意……
> 
> ![paymentwall](https://user-images.githubusercontent.com/8534653/208253546-136679fd-2916-4925-bfa3-e6acbb814a2a.PNG)
> 
> 
> 
> 我现在点了取消，至少两年以后不会给我再续了吧……
> 
> 
> 
> 我没找到怎么在 panda 账户里查看有没有自动续订，只能提醒用 paymentwall 支付的朋友及时查收邮件、取消自动续费！我给 paymentwall 也发了邮件，不知道钱能不能要回来。

坑啊

**Comment by soloice** [comment]
我退款成功了！

**Comment by xxmy7** [comment]
请问没有注册过paymentwall，用的银联无卡支付输的验证码，转到paymentwall的，这种会存在自动续费吗？

**Comment by imokoyyy** [comment]
> 请问没有注册过paymentwall，用的银联无卡支付输的验证码，转到paymentwall的，这种会存在自动续费吗？

一样的情况，蹲一下答案
