### ISSUE TITLE
stripe如何退款，有没有用stripe的

### ISSUE THREAD

**Issue by Nicolerobinn** [PandaVPN/panda#110]

**Comment by Nicolerobinn** [comment]
这特么商家都跑路了，为啥stripe还不给我们直接退款，paymentwall和paypal都直接退款了

**Comment by Nicolerobinn** [comment]
<img width="229" alt="image" src="https://user-images.githubusercontent.com/48322373/210714031-4063a841-09e1-40db-b2fc-821ff3d07683.png">

**Comment by STue123** [comment]
直接联系银行申请信用卡拒付 罚死商家，拒付多了 还有可能商家信用卡收款通道被封掉。 信用卡拒付是信用卡组织赋予每个持卡人的保护自己避免交易欺诈的权力

你百度搜索关键词 信用卡拒付 了解一下

https://www.baidu.com/baidu?tn=monline_3_dg&ie=utf-8&wd=%E4%BF%A1%E7%94%A8%E5%8D%A1%E6%8B%92%E4%BB%98

**Comment by STue123** [comment]
你打电话给发卡银行信用卡中心或者直接到银行柜台申请拒付 说这笔交易是盗刷的申请拒付 拒付原因写： 交易欺诈，持卡人未授权的假卡交易。

就可以了 ，拒付以后你的钱立即退回到你的信用卡里面

**Comment by Nicolerobinn** [comment]
> 你打电话给发卡银行信用卡中心或者直接到银行柜台申请拒付 说这笔交易是盗刷的申请拒付 拒付原因写： 交易欺诈，持卡人未授权的假卡交易。
> 
> 就可以了 ，拒付以后你的钱立即退回到你的信用卡里面

我联系了银行，告诉我这笔订单是预付款，没有入账，让我等到实际入账后再联系他们，他们帮我去弄
