### ISSUE TITLE
大家冲，222年7月份通过paymentwall 扣款的，写邮件给paymentwall 退款了

### ISSUE THREAD

**Issue by wiekern** [PandaVPN/panda#118]
收到回信说处理了，等5-7个工作日，不能纵容骗子。
![image](https://user-images.githubusercontent.com/3865455/215307117-ad930291-6f2b-4b5c-9a28-4a3ba905828a.png)

**Comment by lixiang724** [comment]
请问一下如果没有W订单号怎么退款啊。 是通过微信—信用卡付的，显示的是paymentwall

**Comment by wiekern** [comment]
打电话问下信用卡客服他们能看到具体付款平台的订单号不？我有一单也不知道订单号，没给我退，没回复我。我打算问下信用卡客服看看能不能找到。

**Comment by wiekern** [comment]
closed
