### ISSUE TITLE
Panda怎么又复活了,现在又能用了, 就是节点少了, 目前时间2023-03-10

### ISSUE THREAD

**Issue by derrck** [PandaVPN/panda#124]
本来用回之前的老机场, Panda居然又活了...
https://portal.shadowsocks.au/aff.php?aff=62484

**Comment by GuangNian10000** [comment]
能用个ji儿

**Comment by NingNanXin** [comment]
并不能，server unavailable

**Comment by derrck** [comment]
> 并不能，server unavailable

10号是可以的, 现在弹出了需要升级账号

起码是有变化了, 不知道是跑回来了, 还是换人接手了

**Comment by derrck** [comment]
不知道是跑回来了, 还是换人接手了
