### ISSUE TITLE
忽然无法登录了

### ISSUE THREAD

**Issue by Reniastyc** [PandaVPN/panda#19]
时间是2020/08/30，下午用还正常，晚上忽然就无法登录了，电脑端和手机端都炸了。

不知道是甚么原因，有没有客服解答一下。

**Comment by Reniastyc** [comment]
因为无法登录，所以暂时也没有办法使用客户端的反馈功能，非常神秘。

**Comment by PandaVPN** [comment]
您好，由于注册量太大导致的。技术人员已经修复，请重新登录使用。若是仍有问题，可以通过邮箱panda7x24@gmail.com联系客服解决。
