### ISSUE TITLE
Feature request: add an item to macOS menu bar icon drop down menu, show Pandas Window

### ISSUE THREAD

**Issue by complyue** [PandaVPN/panda#21]
I'd like the Dock icon kept hidden always, but the drop down menu from menu bar icon don't have the option to show status, open settings dialog etc.

I'd also like to see Current Server: status shown from the menu bar icon/drop down, but I want the most is an item to show the main window without showing the Dock icon first.

**Comment by PandaVPN** [comment]
Hi, thanks for your support. We've forwarded your message to our PM, they'll check about it.
