### ISSUE TITLE
linux 客户端无法启动

### ISSUE THREAD

**Issue by a1012112796** [PandaVPN/panda#26]
您好， 这两天ubuntu 客户端突然无法启动，请问可能是什么原因，谢谢！
![Peek 2020-12-06 13-55](https://user-images.githubusercontent.com/25342410/101272842-eb90f800-37ca-11eb-83cc-a4d3fac2a1da.gif)

![image](https://user-images.githubusercontent.com/25342410/101469496-cb566a00-397f-11eb-84c2-5cd72679c379.png)

ubuntu版本: 20.04

**Comment by a1012112796** [comment]
@PandaVPN

**Comment by PandaVPN** [comment]
Hi,  We’re here for you and want to help. We don’t quite understand what
issue you are reporting. Can you tell us a little more about this, please?


Best Regards,
————————————————
PandaVPN Team

**Comment by TimYi** [comment]
@PandaVPN I also use ubuntu client, and met some problem today. I can't login, this is the error:

![loginError](https://user-images.githubusercontent.com/7494892/101570722-f7223000-3a11-11eb-9d04-54883fb25160.png)

@a1012112796 do you have the same problem, or other problem? You can make a screen shot, and drag it into your comment. 

@a1012112796 你也是ubuntu启动登录不了么？如果是其它问题，你可以截图，拖拽到评论中。

**Comment by TimYi** [comment]
@PandaVPN I successfully connected to panda vpn now, don't what's wrong in the last few minutes.

**Comment by a1012112796** [comment]
@PandaVPN 您好，是软件输出第一条消息后，就卡死了，无ui窗口显示，ps 显示处于休眠状态，相关截图已在第一条评论中添加 https://github.com/PandaVPN/panda/issues/26#issue-757856115  .不太清楚是为什么. 之前使用一直是正常的.这两天突然打不开了。请问该软件有依赖软件要求吗?谢谢.

**Comment by PandaVPN** [comment]
We apologize for the brief downtime and inconvenience, everything is back
to normal now.


Best Regards,
————————————————
PandaVPN Team
