### ISSUE TITLE
在软路由上使用，有解决方案吗

### ISSUE THREAD

**Issue by yinjun622** [PandaVPN/panda#27]

**Comment by PandaVPN** [comment]
您好，目前暂时不支持软路由使用的。您可以在Windows、安卓、Mac、iOS、Linux、安卓TV等设备安装使用。您可以直接下载使用，如果还有其他问题，可以通过应用内反馈联系客服

**Comment by PandaVPN** [comment]
好的， 后续会退出更多版本，感谢您的支持


Best Regards,
————————————————
PandaVPN Team

**Comment by PandaVPN** [comment]
好的， 后续会推出更多版本，感谢您的支持



Best Regards,
————————————————
PandaVPN Team
