### ISSUE TITLE
manjaro上不能使用

### ISSUE THREAD

**Issue by pi12138** [PandaVPN/panda#28]
我进行了测试发现在debian系的发行版是可以正常使用的，测试版本：Mint19，Deepin20。希望可以解决一下这个问题，既然发行的是appimage的包，希望的是可以在任意的linux发行版上运行.

**Comment by PandaVPN** [comment]
您好，我们目前只专门适配了Ubuntu系统的，我会把此问题反映给产品部门，尽请期待。如果还有其他问题，可以通过应用内反馈联系客服。

**Comment by zhouzhinian** [comment]
希望再跟进一下，manjaro用不了。

**Comment by PandaVPN** [comment]
您好，请问是可以连接线路无法上网吗？目前该系统技术仍在适配


Best Regards,
————————————————
PandaVPN Team

**Comment by zhouzhinian** [comment]
可以连上，国内网站正常。就是不能翻墙！！

**Comment by zhouzhinian** [comment]
都折腾过了，连不上。发自我的华为平板-------- 原始邮件 --------发件人： PandaVPN <notifications@github.com>日期： 2021年1月21日周四 09:29收件人： PandaVPN/panda <panda@noreply.github.com>抄送： zhouzhinian <zhou_zhinian@163.com>, Comment <comment@noreply.github.com>主    题： Re: [PandaVPN/panda] manjaro上不能使用 (#28)

您好，您打开全局模式更换浏览器试下呢











Best Regards,



————————————————



PandaVPN Team











On Thu, Jan 21, 2021 at 3:18 AM zhouzhinian <notifications@github.com>



wrote:

**Comment by PandaVPN** [comment]
除了manjaro ，别的网页和应用可以正常访问吗？
您具体连接的哪条线路？

Best Regards,
————————————————
PandaVPN Team

**Comment by zhouzhinian** [comment]
全局模式也试过了，都连不上哦换过各样的浏览器也不行发自我的华为手机-------- 原始邮件 --------发件人： PandaVPN <notifications@github.com>日期： 2021年1月21日周四 11:01收件人： PandaVPN/panda <panda@noreply.github.com>抄送： zhouzhinian <zhou_zhinian@163.com>, Comment <comment@noreply.github.com>主    题： Re: [PandaVPN/panda] manjaro上不能使用 (#28)

除了manjaro ，别的网页和应用可以正常访问吗？



您具体连接的哪条线路？







Best Regards,



————————————————



PandaVPN Team











On Thu, Jan 21, 2021 at 10:48 AM zhouzhinian <notifications@github.com>



wrote:

**Comment by PandaVPN** [comment]
您好，您发送日志并提供一下您的数字ID，我们请技术查看


Best Regards,
————————————————
PandaVPN Team

**Comment by zhouzhinian** [comment]
好的。发自我的华为手机-------- 原始邮件 --------发件人： PandaVPN <notifications@github.com>日期： 2021年1月21日周四 11:51收件人： PandaVPN/panda <panda@noreply.github.com>抄送： zhouzhinian <zhou_zhinian@163.com>, Comment <comment@noreply.github.com>主    题： Re: [PandaVPN/panda] manjaro上不能使用 (#28)

您好，您发送日志并提供一下您的数字ID，我们请技术查看











Best Regards,



————————————————



PandaVPN Team











On Thu, Jan 21, 2021 at 11:49 AM zhouzhinian <notifications@github.com>



wrote:

**Comment by PandaVPN** [comment]
您好，请问您已发送日志了吗？


Best Regards,
————————————————
PandaVPN Team

**Comment by hunterzju** [comment]
在manjaro上/tmp/Panda*/linuxtrd/privoxy这个程序缺少libpcre.so.3的动态库:
```
	linux-vdso.so.1 (0x00007ffe54eb8000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fc1b51f9000)
	libpcre.so.3 => not found
	libpcreposix.so.3 => not found
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc1b51d8000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc1b500b000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc1b5482000)
```
手动将libpcre.so复制为libpcre.so.3后显示缺少符号：`pcreposix_regexec`，下载了pcre源码检查过各个版本都没这个函数，求开发辛苦看下啥情况，没有梯子好难受。。。

**Comment by PandaVPN** [comment]
您好，之前改动过什么吗？从什么时候开始无法使用的


Best Regards,
————————————————
PandaVPN Team

**Comment by hunterzju** [comment]
> 在manjaro上/tmp/Panda*/linuxtrd/privoxy这个程序缺少libpcre.so.3的动态库:
> 
> ```
> 	linux-vdso.so.1 (0x00007ffe54eb8000)
> 	libz.so.1 => /usr/lib/libz.so.1 (0x00007fc1b51f9000)
> 	libpcre.so.3 => not found
> 	libpcreposix.so.3 => not found
> 	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc1b51d8000)
> 	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc1b500b000)
> 	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc1b5482000)
> ```
> 
> 手动将libpcre.so复制为libpcre.so.3后显示缺少符号：`pcreposix_regexec`，下载了pcre源码检查过各个版本都没这个函数，求开发辛苦看下啥情况，没有梯子好难受。。。

这不是我改动导致的，是pandavpn一直在linux的一个发行版manjaro中无法使用，以上是我排查发现的问题，求技术小哥解决下兼容性问题。

**Comment by PandaVPN** [comment]
好的，我们反馈技术人员


Best Regards,
————————————————
PandaVPN Team

**Comment by pi12138** [comment]
> > 在manjaro上/tmp/Panda*/linuxtrd/privoxy这个程序缺少libpcre.so.3的动态库:
> > ```
> > 	linux-vdso.so.1 (0x00007ffe54eb8000)
> > 	libz.so.1 => /usr/lib/libz.so.1 (0x00007fc1b51f9000)
> > 	libpcre.so.3 => not found
> > 	libpcreposix.so.3 => not found
> > 	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc1b51d8000)
> > 	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc1b500b000)
> > 	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc1b5482000)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 手动将libpcre.so复制为libpcre.so.3后显示缺少符号：`pcreposix_regexec`，下载了pcre源码检查过各个版本都没这个函数，求开发辛苦看下啥情况，没有梯子好难受。。。
> 
> 这不是我改动导致的，是pandavpn一直在linux的一个发行版manjaro中无法使用，以上是我排查发现的问题，求技术小哥解决下兼容性问题。

我去年就反馈了，然而并没有啥回应

**Comment by hunterzju** [comment]
> 在manjaro上/tmp/Panda*/linuxtrd/privoxy这个程序缺少libpcre.so.3的动态库:
> 
> ```
> 	linux-vdso.so.1 (0x00007ffe54eb8000)
> 	libz.so.1 => /usr/lib/libz.so.1 (0x00007fc1b51f9000)
> 	libpcre.so.3 => not found
> 	libpcreposix.so.3 => not found
> 	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc1b51d8000)
> 	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc1b500b000)
> 	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc1b5482000)
> ```
> 
> 手动将libpcre.so复制为libpcre.so.3后显示缺少符号：`pcreposix_regexec`，下载了pcre源码检查过各个版本都没这个函数，求开发辛苦看下啥情况，没有梯子好难受。。。

目前暂时找到了个临时解决方法：在chrome上用SwitchyOmega插件做一次代理转换：
代理协议socket5，服务器地址填127.0.0.1，端口1090
这样可以在浏览器里翻墙，但是还没法解决git加速问题；
原因是这样的：pandavpn使用ss-local开代理，但是走的是socket5协议，我们一般访问走http协议，因此还需要再开一个socket5到http的代理，linux下用privoxy可以实现，但是在manjaro下有个包（就libpcre这货，貌似是正则匹配用到的）不兼容，privoxy开不起来，折腾了下自己起privoxy，但是好像没生效，不知道有没有大神懂的，可以交流下。

**Comment by PandaVPN** [comment]
好的，我们提交到技术人员，非常感谢您的反馈。


Best Regards,
————————————————
PandaVPN Team
