### ISSUE TITLE
登录失败， 服务器错误

### ISSUE THREAD

**Issue by feWei1997** [PandaVPN/panda#32]
登录失败， 服务器错误

**Comment by chuanquanzi** [comment]
我的也是，今天下午突然不能登录了，刚买了两年的会员，坐标郑州。官方赶紧解释下怎么回事！！！

**Comment by XiaMoTea** [comment]
PC端还可以使用

**Comment by Superskyyy** [comment]
pc退出去之后就不行了 登录不上显示无网络 手机也不行了

**Comment by a635746860** [comment]
我这边OK了， 估计是服务器波动 @Superskyyy @chuanquanzi @XiaMoTea  🤔️

**Comment by Superskyyy** [comment]
> 我这边OK了， 估计是服务器波动 @Superskyyy @chuanquanzi @XiaMoTea  🤔️

我本来在续费的 以为突然碰上跑路了没敢付钱…
