### ISSUE TITLE
为什么用启动vpn后wifi环境下可以翻墙，但是用网线宽带连接却不行？

### ISSUE THREAD

**Issue by Luke-Liu-01** [PandaVPN/panda#42]

**Comment by 13699796386** [comment]
请问下你是怎么做到wifi环境下可以翻墙的？我用一个台式机安装Ubuntu做软路由，有线提供外网访问，无线提供热点，现在的问题是在Ubuntu系统里可以正常翻墙，但外部设备连接无线热点可以正常上网却无法翻墙了。

**Comment by Luke-Liu-01** [comment]
> 请问下你是怎么做到wifi环境下可以翻墙的？我用一个台式机安装Ubuntu做软路由，有线提供外网访问，无线提供热点，现在的问题是在Ubuntu系统里可以正常翻墙，但外部设备连接无线热点可以正常上网却无法翻墙了。

不好意思，我也不清楚。我们两个的问题恰恰相反，我认为可能是某些网络设置处理问题。

**Comment by PandaVPN** [comment]
您好，我们对WiFi和网线宽带没有任何限制，请您检查一下网线宽带拨号名称是否是中文，如果是，请更改成英文后重启电脑即可。

**Comment by Luke-Liu-01** [comment]
> 您好，我们对WiFi和网线宽带没有任何限制，请您检查一下网线宽带拨号名称是否是中文，如果是，请更改成英文后重启电脑即可。

改了之后果然可以了，感谢！！！

**Comment by PandaVPN** [comment]
不客气的


Best Regards,
————————————————
PandaVPN Team

**Comment by PandaVPN** [comment]
Hi, this is the customer service team of PandaVPN. What can we do for you?


Best Regards,
————————————————
PandaVPN Team
