### ISSUE TITLE
无法退款

### ISSUE THREAD

**Issue by imzikang** [PandaVPN/panda#50]
客服一直不回复，导致无法退款![IMG_20210704_134717.jpg](https://user-images.githubusercontent.com/86904478/124374501-5ad1ba80-dcce-11eb-99db-76631e064e54.jpg)
邮箱2904646632@qq.com
@PandaVPN

**Comment by PandaVPN** [comment]
您好，请问您在使用中遇到什么问题了？我们可以为您解决问题的。


Best Regards,
————————————————
PandaVPN Team
