### ISSUE TITLE
linux上运行appimage报错

### ISSUE THREAD

**Issue by lelelemonade** [PandaVPN/panda#8]
./panda3.4.0-x86_64.appimage: symbol lookup error: /tmp/.mount_panda3rPQSLT/plugins/imageformats/libqico.so: undefined symbol: _ZdlPvm, version Qt_5
希望告诉我怎么办

**Comment by PandaVPN** [comment]
您好，请把Linux系统版本信息通过客服邮箱panda7x24@gmail.com告知我们。
