### ISSUE TITLE
尼玛的 连官方网站都关了 你们可以登录他的官网吗

### ISSUE THREAD

**Issue by jetty-guo** [PandaVPN/panda#97]

**Comment by Genius669** [comment]
可以登录，需要代理才能进

**Comment by antcarryele** [comment]
代理可以，这个[Pigcha VPN](http://run.co2fun.com/register?share_id=b2226a4c-6a69-486c-b923-28f89d4c64d2) 还不错可以按照流量和时长，浏览无压力。有免费200M可以应急 自己注册，模式自己选择。 用代理直接上去

**Comment by jetty-guo** [comment]
没有关闭 但还是访问不了
